spring:
  application:
    name: cyp-ai-role-chat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cyp_ai_role_chat
    username: root
    password: 1234
server:
  port: 8121
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cyp.cypairolechat.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
