# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-c7623a1b4e744d30b1f634317fe77587
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192

# application.yml
baidu:
  speech:
    app-id: 120152683
    api-key: 7AvpeoLeLZsgNmnOektnoSWj
    secret-key: VULTFxN0qcrcfUMgYkkAxdknpBghRovY
